.rtd-environment.yml
.travis.yml
README.rst
scintillometry/_astropy_init.py
scintillometry/tests/coveragerc
scintillometry/tests/setup_package.py
setup.cfg

Set up Travis, Coveralls, RTD files.  Add Baseband as a required package.

Test environment setup

---

.rtd-environment.yml

Hoping it fixes RTD build errors.

ReadtheDocs build environment change.

---

.travis.yml

Test to see if we can add pyfftw to Coveralls.

Add pyfftw to Coveralls.

---

scintillometry/fourier/tests/test_fourier.py

Increase coverage by testing rFFT frequencies, repr and copying.

Expand Fourier module test coverage

---

docs/index.rst
docs/tasks/square.rst
scintillometry/square.py
scintillometry/tests/test_square.py

Revised after refactoring, and taking into account all comments in #13.  Because of our earlier rebasing shenanigans, I couldn't rebase the `make_squarer` branch without encountering many conflicts, so I just made a new one.  I'll close the old PR.

Revised squaring module

---

docs/helpers/fourier.rst
scintillometry/base.py
scintillometry/channelize.py
scintillometry/fourier/base.py
scintillometry/fourier/numpy.py
scintillometry/fourier/pyfftw.py
scintillometry/fourier/tests/test_fourier.py
scintillometry/functions.py
scintillometry/generators.py
scintillometry/tests/test_base.py
scintillometry/tests/test_channelize.py
scintillometry/tests/test_dispersion.py
scintillometry/tests/test_functions.py
scintillometry/tests/test_generators.py

Define `freq` and `sideband` properties for all tasks, and propagate them appropriately.
Plus quite a bit of cleanup.

Define frequency/sideband and use it in Channelize.

---

scintillometry/channelize.py
scintillometry/fourier/__init__.py
scintillometry/fourier/base.py
scintillometry/fourier/tests/test_fourier.py
scintillometry/tests/test_channelize.py

Also fix a bug in Dechannelize that was exposed by using pyfftw.
fixes #15

Set up a default fft maker.

---

.travis.yml

This is like for the others builds.

Try using conda depencency of pyfftw

---

scintillometry/base.py
scintillometry/tests/test_basedata.py

@luojing1211 - just a first very rough cut at a baseclass. I think in addition we can define addition to also add `count` (if both arguments have it).

Very simple implementation of a BaseData class with count attribute.

---

docs/index.rst
docs/tasks/dispersion.rst
docs/tasks/shaping.rst
scintillometry/base.py
scintillometry/shaping.py
scintillometry/tests/test_base.py
scintillometry/tests/test_shaping.py

@luojing1211 - here's another one to look at...

Sample Shape changes, e.g., to ensure pol/freq etc are on separate axes.

---

AUTHORS.rst
README.rst

Simultaneously removed myself from the help contact list in README.rst.  Probably shouldn't be merged until #38.

Add luojing1211 in README.rst and AUTHORS.rst

---

scintillometry/base.py
scintillometry/integration.py

The name is a bit ugly, but don't want to be getting `frequency` of an `ih` in multiple places...

Factor out a BaseTaskBase for integration.

---

scintillometry/base.py
scintillometry/channelize.py
scintillometry/dispersion.py

Does not do integration, since that will be a separate PR changing a lot more.

Move shape check with samples_per_frame higher up.

---

scintillometry/integration.py

On real data, my interpolation to calculate offsets got stuck; this one should not be able to do that... (no test, since not so easy to set up).

Use improved offset calculation, unable (hopefully) to get stuck.

---

scintillometry/shaping.py

Ensure GetItem is visible in docs.

---

scintillometry/shaping.py

Docs were taken from ReshapeAndTranspose.

Small update.

---

scintillometry/base.py
scintillometry/functions.py
scintillometry/shaping.py
scintillometry/tests/test_functions.py

Ensure `frequency` and `sideband` are dealt with correctly in `Power`. As part of this, the code now generally ensures all those attributes have minimal shape (i.e., don't have the same values along any axis).
fixes #60

Power shape fix

---

scintillometry/base.py
scintillometry/integration.py
scintillometry/tests/test_integration.py

Allow one to pass in a start time or offset for integration.

---

scintillometry/generators.py
scintillometry/tests/test_generators.py

Add polarization argument to all generators.

---

docs/index.rst
docs/tasks/convolution.rst
scintillometry/base.py
scintillometry/convolution.py
scintillometry/dispersion.py
scintillometry/tests/test_convolution.py
scintillometry/tests/test_dispersion.py

Also in preparation for the PFB work. Already factored out some common stuff with `Dispersion` but more could be done.

Convolution

---

scintillometry/channelize.py
scintillometry/convolution.py
scintillometry/dispersion.py
scintillometry/fourier/base.py
scintillometry/fourier/pyfftw.py

Partially addresses #81 (one needless array creation less).

Pyfftw memory consumption

---

scintillometry/phases/core.py
scintillometry/phases/pint_toas.py

This because it currently breaks the sphinx build. Not very elegant but for now it will have to do...

Move pint import inside code that uses it.

---

README.rst

Noticed it was missing as I was e-mailing Mudi and Keith.

Add link to documentation to README

---

docs/install.rst

Set minimum version for PyFFTW.

---

scintillometry/tests/test_base.py

Aiming to reduce the noise when running tests locally.

Ensure files are always closed in tests.

---

.travis.yml
docs/install.rst
scintillometry/integration.py
scintillometry/phases/__init__.py
scintillometry/phases/core.py
scintillometry/phases/phase.py
scintillometry/tests/test_integration.py
scintillometry/tests/test_phase_class.py
scintillometry/tests/test_phases.py

With the idea to move this up to PINT, to replace its phase class.
fixes #71

Add a double-precision Phase class

---

scintillometry/tests/test_phases.py
scintillometry/tests/test_pint_toas.py

Missed a rename in our initial commit! Rather sloppy review!

Ensure pint toa tests are actually run.

---

scintillometry/base.py
scintillometry/tests/test_base.py
scintillometry/tests/test_shaping.py

Also allows to reset the start time, e.g., to apply a clock correction.

Simple wrapper that allows one to set frequency, etc., attributes.

---

scintillometry/__init__.py
scintillometry/data/PsrfitsDocumentation.html
scintillometry/io/psrfits/core.py
scintillometry/io/psrfits/hdu.py
scintillometry/io/psrfits/psrfits_htm_parser.py
scintillometry/tests/test_io_psrfits_read.py
scintillometry/tests/test_io_psrfits_setter.py
setup.py

Initialize pull request for the PSRFITs writer. 
This PR covers the PSRFITS header HDU initialization and setters.

Psrfits write

---

scintillometry/combining.py
scintillometry/tests/test_combining.py

Allow combine tasks to work just on time common to streams.

---

scintillometry/base.py
scintillometry/io/psrfits/hdu.py
scintillometry/tests/test_base.py
scintillometry/tests/test_io_psrfits_read.py
scintillometry/tests/test_io_psrfits_setter.py

fixes #108
Also ensures both are copies, not views of the inputs.

Ensure that both frequency and sideband are passed in.

---

docs/index.rst
docs/tasks/sampling.rst
scintillometry/combining.py
scintillometry/sampling.py
scintillometry/tests/test_sampling.py

Partially addresses #100.
@theXYZT - would this be what you were looking for, for extracting B1937 giant pulses?

Add a resample task.

---

scintillometry/phases/core.py
scintillometry/phases/pint_toas.py
scintillometry/tests/test_phases.py
scintillometry/tests/test_pint_toas.py

Allow array-valued frequencies in PintPhase

---

.travis.yml
scintillometry/data/__init__.py
scintillometry/io/psrfits/hdu.py
scintillometry/io/psrfits/psrfits_htm_parser.py
scintillometry/tests/test_io_psrfits_setter.py

This PR is a small upgrade on the PSRFITS PSRSUBINT hdu. Here are what it does:
1. Adds the data columns 
2. Allows one set data to the data columns
3. Covert an HDU to an astropy io hdulist

PSRFITS PSRHdu data write

---

scintillometry/base.py

Adjust docstring to .close() to mention that it does not close underlying source

---

scintillometry/base.py
scintillometry/tests/test_base.py

This would be bad if count were an array scalar or dimensionless Quantity. Ensures the problem found for baseband does not recur here (see https://github.com/mhvk/baseband/issues/370#issuecomment-577916056)

Ensure count is not changed in-place.

---

scintillometry/integration.py

Mention need for large samples_er_frame in integration [docs only]

---

.travis.yml
setup.cfg

This so that travis starts to test it again too.

Add pint to all dependencies.

---

scintillometry/io/hdf5/__init__.py
scintillometry/io/hdf5/base.py
scintillometry/io/hdf5/frame.py
scintillometry/io/hdf5/header.py
scintillometry/io/hdf5/tests/test_hdf5.py

Allow override of shape when initializing an HDF5 Header from a template.

---

.travis.yml
docs/install.rst
scintillometry/tests/iers_up_to_date.py
scintillometry/tests/test_base.py
scintillometry/tests/test_phases.py
scintillometry/tests/test_pint_toas.py
setup.cfg
tox.ini

This is to check whether it resolves the cron failures for oldest dependencies.
Need to move devdeps back to cron if tests pass.

Use pint from pypi

---

scintillometry/phases/predictor.py
scintillometry/tests/test_phases.py

Needed a small correction for Predictor.

Ensure that phase predictions can deal with multi-dimensional times.

---

scintillometry/phases/predictor.py
scintillometry/tests/test_predictor.py

Fix Overflow Error on systems where C long is int32

---

scintillometry/phases/core.py

Needed because of https://github.com/nanograv/PINT/pull/685

Become agnostic to the units of PINT phases

---

scintillometry/generators.py

Feel like I changed this before in the other direction... Sigh.

Refer to random state in its nominal location

---

.travis.yml
scintillometry/io/hdf5/base.py
scintillometry/io/hdf5/frame.py
scintillometry/io/hdf5/payload.py
scintillometry/io/hdf5/tests/test_hdf5.py
setup.cfg
tox.ini

Also fix the CI matrix so that we always test with baseband dev

Fix HDF5 to work with baseband dev

---

.travis.yml
scintillometry/io/hdf5/tests/test_hdf5.py
scintillometry/tests/test_entry_points.py
scintillometry/tests/test_phases.py
scintillometry/tests/test_pint_toas.py
setup.cfg

Adds also the baseband.tasks entry points.

Baseband plugin

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/combining.py
baseband_tasks/shaping.py
baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_combining.py
baseband_tasks/tests/test_generators.py
baseband_tasks/tests/test_shaping.py
docs/tasks/shaping.rst

Also makes combining quite a bit easier.

Allow slicing of streams

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/channelize.py
baseband_tasks/combining.py
baseband_tasks/conversion.py
baseband_tasks/convolution.py
baseband_tasks/dispersion.py
baseband_tasks/functions.py
baseband_tasks/integration.py
baseband_tasks/sampling.py
baseband_tasks/shaping.py
baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_channelize.py
baseband_tasks/tests/test_combining.py
baseband_tasks/tests/test_conversion.py
baseband_tasks/tests/test_convolution.py
baseband_tasks/tests/test_functions.py
baseband_tasks/tests/test_generators.py
baseband_tasks/tests/test_integration.py
baseband_tasks/tests/test_sampling.py
baseband_tasks/tests/test_shaping.py

This may not stay the same, but is definitely better than nothing:
```
In [6]: stack                                                                                          
Out[6]: 
Stack(ih,
n_phase=64,
samples_per_frame=1024)
ih: Integrate(ih,
step=0.015625 cycle,
phase=<function phase at 0x7f5e0c7331f0>,
samples_per_frame=65536)
ih: Square(ih)
ih: Dedisperse(ih,
dm=-71.02227638 pc / cm3,
reference_frequency=331.6875 MHz,
samples_per_frame=7368110)
ih: SetAttribute(ih,
frequency=[327.    330.125 333.25  336.375] MHz,
sideband=1,
polarization=[['L'], ['R']],
shape=(1023934464, 2, 4))
ih: <GUPPIStreamReader name=puppi_58245_B1937+21_0799.0010.raw offset=0
sample_rate=3125000.0 Hz, samples_per_frame=7999488,
sample_shape=SampleShape(npol=2, nchan=4), bps=8, …
```

Repr and str

---

CHANGES.rst
baseband_tasks/phases/predictor.py
baseband_tasks/tests/test_predictor.py

Replaces #201 (as I cannot seem to push to that PR).
Fixes #200

Fix overly stringest test on time intervals in polyco 

---

CHANGES.rst
baseband_tasks/generators.py
baseband_tasks/tests/test_convolution.py
baseband_tasks/tests/test_generators.py

This makes the stream reproducible for a given seed.
fixes #169
cc @theXYZT - thanks!

Switch noise generator to new numpy scheme, using Philox bit generator.

---

docs/conf.py

Removing non-functioning work-around

---

baseband_tasks/phases/phase.py
baseband_tasks/tests/test_phase_class.py

Also fix __str__ for scalar case

---

baseband_tasks/phases/predictor.py

Replicates #215 by @theXYZT, but with an updated reference link.

Predictor polyco docstring

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/integration.py
baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_convolution.py
baseband_tasks/tests/test_integration.py

This means less data is used even if large `samples_per_frame` is used.
Fixes #189

Allow incomplete last frames

---

baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_channelize.py
baseband_tasks/tests/test_combining.py
baseband_tasks/tests/test_conversion.py
baseband_tasks/tests/test_convolution.py
baseband_tasks/tests/test_dispersion.py
baseband_tasks/tests/test_dm.py
baseband_tasks/tests/test_entry_points.py
baseband_tasks/tests/test_functions.py
baseband_tasks/tests/test_generators.py
baseband_tasks/tests/test_integration.py
baseband_tasks/tests/test_phase_class.py
baseband_tasks/tests/test_phases.py
baseband_tasks/tests/test_pint_toas.py
baseband_tasks/tests/test_predictor.py
baseband_tasks/tests/test_sampling.py
baseband_tasks/tests/test_shaping.py
baseband_tasks/tests/test_simulate.py

Use absolute package imports in tests

---

CHANGES.rst
baseband_tasks/sampling.py
baseband_tasks/tests/test_sampling.py

Shift time samples at each channel. 
ps: just start this PR so that we have a place to discuss it.

Sample shift

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/channelize.py
baseband_tasks/combining.py
baseband_tasks/conversion.py
baseband_tasks/dispersion.py
baseband_tasks/generators.py
baseband_tasks/io/hdf5/header.py
baseband_tasks/io/psrfits/core.py
baseband_tasks/tests/test_base.py

This opens up the possibility to define other attributes easily, such as the shifts in `SimpleShift`.

Meta attributes for frequency, sideband, and polarization

---

CHANGES.rst
baseband_tasks/phases/pint_toas.py
baseband_tasks/tests/test_phases.py

@luojing1211 - does this make sense?
fixes #235

No longer pass on control parameters to toa.TOA

---

baseband_tasks/sampling.py
baseband_tasks/tests/test_sampling.py

This since all the tasks have names that are verbs, implying actions.

Rename SampleShift to ShiftSamples.

---

CHANGES.rst
baseband_tasks/dispersion.py
baseband_tasks/tests/test_dispersion.py

A correctly rebased disperse shift branch. The old PR #232 is moved to this one.

add disperse shift

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/convolution.py
baseband_tasks/dispersion.py
baseband_tasks/fourier/numpy.py
baseband_tasks/fourier/pyfftw.py
baseband_tasks/pfb.py
baseband_tasks/sampling.py
baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_dispersion.py

Ensure that they always are efficient for tasks using padding.

Sanitize fft sizes
