.rtd-environment.yml

The last change didn't result in a successful build, but I made some further changes that should now make it work.
I don't know why we need to install `sphinx_astropy` - perhaps the Python 3 requirement forces it?  In any case, RTD complains if it's not included under `pip`.

Further ReadTheDocs build environment changes.

---

README.rst
docs/index.rst

(Hopefully) fix badges reporting 'unknown' in Readme.rst, and added badges to the docs.
Oddly, despite there being a cron job, Scintillometry has never built the master branch, which is why Travis reports its build status as unknonwn and Coveralls can't track anything.  I manually triggered a master build on Travis, which alleviated the problem.  @mhvk, could you fiddle with the cron job to see if it can build regularly?

Fix badges reporting 'unknown'.

---

docs/base/index.rst
docs/channelize/index.rst
docs/conf.py
docs/index.rst
scintillometry/base/base.py
scintillometry/base/tests/test_base.py
scintillometry/channelize/__init__.py
scintillometry/channelize/base.py
scintillometry/channelize/tests/test_channelize.py
scintillometry/fourier/base.py
scintillometry/fourier/pyfftw.py

Work in progress, but wanted to show you what I have so far.
The channelizer currently works if fed a Baseband stream reader.  It itself acts like a stream on top of the Baseband stream, and defines its own channelized complete sample shape as:
```
(n_fourier_chan,) + fh.sample_shape
```
where the number of Fourier channels is user-defined.  It also defines a start time, stop time, sample shape, ndim and shape all in accordance with the channelized sample definition.
In the backend, it utilises a block system in the same way Baseband stream readers use frames: whenever a new block is reached a (currently user-defined) number of channelized samples is calculated.  These channelized samples are held in `self._block` to be used as needed by the user, until the user seeks out of the block's …

Base Analysis Module Channelizer (WIP)

---

ah_bootstrap.py
scintillometry/_astropy_init.py
setup.cfg
setup.py

Mostly as I hoped it would help ensure doctests in `docs/` actually get run - it doesn't but might as well merge it.

Update following astropy package template.

---

scintillometry/_astropy_init.py

This one-line change prevents pytest from picking up the test function as a test. See astropy/package-template#373.
*This is an automated fix by @pllim. If this is opened in error, please close without merge.*

Prevent pytest from picking up test function as a test

---

scintillometry/base.py
scintillometry/functions.py
scintillometry/tests/test_functions.py

This one keeps cross-terms, following what appears to be standard convention (from `scintellometry`).
@luojing1211 - could you have a look?

Add a Power task, which squares while keeping polarization cross-products

---

scintillometry/base.py

Comparing a unit with something else will invoke an attempt to interpret something else as a unit, which is very costly.

Avoid comparing units with 'time'.

---

scintillometry/base.py
scintillometry/tests/test_generators.py

Found while writing phase folding tests.

Ensure generators can count on offset being correct in _read_frame.

---

docs/index.rst
docs/tasks/integration.rst
scintillometry/integration.py
scintillometry/tests/test_integration.py

This introduces integration by phase bins rather than by time; combined with a reshape that creates a pulse stack.
This builds on #50 which in turn builds on #47. Probably good to get some merged...  @luojing1211?
EDIT: I gave up on keeping #47 and #50 up to date as the classes ended up being taken apart and combined again (in quite a simple `Integrate` class), and I'm fairly sure this is the way to go.

Integration by phase and its use in Stack

---

scintillometry/fourier/tests/test_fourier.py

Should really have done this as part of #89 - add a test that normalisation actually works.

Add test that ortho works for pyfftw.

---

.travis.yml
docs/index.rst
docs/install.rst
docs/tasks/combining.rst
scintillometry/base.py
scintillometry/combining.py
scintillometry/shaping.py
scintillometry/tests/test_combining.py
scintillometry/tests/test_shaping.py

fixes #99
At present, the code insists that the input streams have the same start times. This can be relaxed once we have the ability to extract time slices.

StreamCombiner class

---

scintillometry/base.py
scintillometry/shaping.py
scintillometry/tests/common.py
scintillometry/tests/test_base.py
scintillometry/tests/test_channelize.py
scintillometry/tests/test_combining.py
scintillometry/tests/test_convolution.py
scintillometry/tests/test_functions.py
scintillometry/tests/test_shaping.py

fixes #101 
I realized it was really not logical to delete all underlying filehandles. One should just delete the reference, and if it is the last one held, the file will be deleted and thus closed.
This way, one can use the sample input in multiple pipelines without worrying about the file closing under one's feet.
Note this affects very little actual code, but the tests had to be adapted to always close any data files one opens.

Delete rather than close ih

---

scintillometry/integration.py
scintillometry/phases/phase.py
scintillometry/sampling.py
scintillometry/tests/test_dispersion.py

python round gives float on numpy floats (which may become an issue with astropy 4.0, which changes `.value` to give a numpy float), numpy round is just a needless wrapper for around.

Avoid using python or numpy round

---

docs/io/hdf5/index.rst
scintillometry/io/hdf5/base.py
scintillometry/io/hdf5/header.py
scintillometry/io/hdf5/payload.py
scintillometry/io/hdf5/tests/test_hdf5.py

Using a new `encoded_dtype='c4'` argument.
cc @00rebe - this should be helpful for storing the files around giant pulses.

Allow half-float storage in HDF5 files, also for complex numbers

---

docs/install.rst

I noticed that H5py was missing as an optional library in the documentation. I added a line for it.

Added H5py to the optional requirements in documentation

---

scintillometry/channelize.py
scintillometry/tests/test_channelize.py

As it was, it was ignored which made it impossible to have values not equal to a factor of the input streams samples per frame.

Ensure Channelize samples_per_frame is used for calculating its shape.

---

scintillometry/io/hdf5/header.py
scintillometry/io/hdf5/tests/test_hdf5.py

This since sometimes a given stream may error if trying to access
some information (e.g., trying to calculate a time from a phased
stream, in which sample_rate is in cycles), and in this case it
should still be possible to at least overwrite that property.
partially addresses #150

Don't attempt to get attributes that are passed in as keywords.

---

.travis.yml
setup.cfg
tox.ini

Want to be sure we only install what we actually use, also for testing.

Minimize test dependencies

---

setup.cfg
tox.ini

#170 was not quite right; this fixes it and also removes `pytest-openfiles` until it has been fixed (see #171)

Only get coverage installed if used.

---

baseband_tasks/base.py
baseband_tasks/io/hdf5/base.py

Makes the `.read()` method identical to that of `baseband`.

Refactor read

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/channelize.py
baseband_tasks/conversion.py
baseband_tasks/convolution.py
baseband_tasks/dispersion.py
baseband_tasks/integration.py
baseband_tasks/sampling.py
baseband_tasks/tests/test_base.py
baseband_tasks/tests/test_convolution.py
baseband_tasks/tests/test_sampling.py

The main change is for simple tasks to allow `shape[0]` to be a non-integer multiple of `samples_per_frame` - obviously only for tasks which can handle variable number of samples.

Simplify task base, preparing for slicing

---

CHANGES.rst
baseband_tasks/base.py
baseband_tasks/integration.py
baseband_tasks/shaping.py
baseband_tasks/tests/test_integration.py

Done with the usual indirection, by creating a new _tell_time method which is used by everything that needs times and can be overridden by subclasses.

Fix time for phase integration.

---

baseband_tasks/tests/test_base.py

A time comparison test failed the big-endian run

Allow for 2 ulp precision loss in time comparison

---

setup.cfg
tox.ini

We're now well past 4.0.1 where PINT had trouble.

Use generic 4.0.* for oldest astropy version

---

baseband_tasks/phases/phase.py
baseband_tasks/tests/test_phase_class.py

Fixes #216 
Not very pretty but easiest way to work around fact that `np.array2string` does not allow one to override formatting of structured dtype.

Get Phase.__str__ to work at least in basic fashion

---

CHANGES.rst
baseband_tasks/sampling.py
baseband_tasks/tests/test_sampling.py

Fixes #100 (except the most general case, of using a polyco, etc.)
Also improves the consistency of `Resample`

Shifting, delaying and resampling of streams

---

CHANGES.rst
baseband_tasks/sampling.py
baseband_tasks/tests/test_sampling.py

@luojing1211 - this is what I had in mind for allowing `float` input. I think the usage is quite obvious, and also consistent with how `stream.seek` rounds to the nearest sample too.

Allow float shifts in SampleShift, rounding those to integer.

---

CHANGES.rst
baseband_tasks/io/hdf5/payload.py
baseband_tasks/io/hdf5/tests/test_hdf5.py

As found when trying to create a quick stream reader class for ARO-CHIME baseband dumps

Ensure HDFPayload subclasses can be used directly.

---

CHANGES.rst
baseband_tasks/integration.py
baseband_tasks/tests/test_integration.py

This to avoid name clash in `baseband.tasks` with `combining.Stack`.

Deprecate integration Stack in favour of PulseStack
